# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure Pass - Sponsorship(80529350-ab8a-4ec3-a694-0e7509824aa7)'
    subscriptionId: '80529350-ab8a-4ec3-a694-0e7509824aa7'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'demoweb'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'WebBicep.bicep'
    csmParametersFile: 'WebBicep.parameters.json'
    deploymentMode: 'Incremental'